### ISSUE TITLE
整合Spring,加上@HttpApiScan扫描报错

### ISSUE THREAD

**Issue by wayTofeatures** [dadiyang/http-api-invoker#5]
At least one base package must be specified
	at org.springframework.util.Assert.notEmpty(Assert.java:228) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:269) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.github.dadiyang.httpinvoker.spring.ClassPathHttpApiScanner.doScan(ClassPathHttpApiScanner.java:54) ~[http-api-invoker-1.2.1.jar:?]
	at com.github.dadiyang.httpinvoker.spring.HttpApiConfigurer.postProcessBeanDefinitionRegistry(HttpApiConfigurer.java:100) ~[http-api-invoker-1.2.1.jar:?]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:122) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]

**Comment by dadiyang** [comment]
试试在HttpApiScan的basePackages中设置一下你的包路径

**Comment by wayTofeatures** [comment]
@HttpApiScan 有这个注解 的bean 都获取不到，
HttpApiConfigurer.postProcessBeanDefinitionRegistry 第一行获取到bean size 为0

**Comment by dadiyang** [comment]
HttpApiScan这个注解类似spring中的ComponentScan，是用来开启包扫描的。全局一般只有一个哦。你定义的接口上面应该打HttpApi注解
