### ISSUE TITLE
mock的时候,包json 反序列化异常

### ISSUE THREAD

**Issue by shyding** [dadiyang/http-api-invoker#8]
com.alibaba.fastjson.JSONException: can not cast to JSONObject.
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:249)
	at com.github.dadiyang.httpinvoker.requestor.ResultBeanResponseProcessor.process(ResultBeanResponseProcessor.java:60)

**Comment by dadiyang** [comment]
你用的是哪个版本？升级到最新版本试试
